# Generated by Django 4.2.19 on 2025-02-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='source_type',
            field=models.CharField(choices=[('rtsp', 'RTSP'), ('mjpg', 'MJPG')], default='rtsp', max_length=10),
        ),
    ]
