# Generated by Django 4.2.19 on 2025-02-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_videosource_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='is_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videosource',
            name='recording_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videosource',
            name='watermark_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
