# Generated by Django 4.2.19 on 2025-02-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_videosource_is_recording_videosource_recording_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosource',
            name='is_recording',
        ),
        migrations.RemoveField(
            model_name='videosource',
            name='output_url',
        ),
        migrations.RemoveField(
            model_name='videosource',
            name='recording_file',
        ),
        migrations.RemoveField(
            model_name='videosource',
            name='watermark_text',
        ),
        migrations.AlterField(
            model_name='videosource',
            name='source_type',
            field=models.CharField(choices=[('rtsp', 'RTSP'), ('mjpg', 'MJPG')], max_length=50),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='url',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='recordings/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_app.videosource')),
            ],
        ),
    ]
