# Generated by Django 4.2.19 on 2025-02-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_remove_videosource_is_recording_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='recording',
            old_name='file_path',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='videosource',
            name='source_type',
        ),
        migrations.AlterField(
            model_name='videosource',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
