# Generated by Django 4.2.19 on 2025-02-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_rename_timestamp_recording_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='source_type',
            field=models.CharField(choices=[('rtsp', 'RTSP'), ('mjpg', 'MJPG')], default='rtsp', max_length=10),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
