# Generated by Django 4.2.19 on 2025-02-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0007_videosource_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosource',
            name='source_type',
            field=models.CharField(choices=[('rtsp', 'RTSP'), ('mjpg', 'MJPG'), ('mpd', 'MPEG-DASH')], default='rtsp', max_length=10),
        ),
    ]
